CREATE DATABASE IF NOT EXISTS gobook;

USE gobook;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS follower;

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  nick VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS follower (
  userId INT NOT NULL,
  followerId INT NOT NULL,
  FOREIGN KEY (userId) 
    REFERENCES user (id) 
      ON DELETE CASCADE,
  FOREIGN KEY (followerId) 
    REFERENCES user (id) 
      ON DELETE CASCADE,

  PRIMARY KEY (userId, followerId)
) ENGINE=INNODB;